#!/usr/bin/ruby
# runs the javascript test

cd = File.expand_path(File.dirname(__FILE__))

server_pid = fork do
  puts "Starting server"
  exec "#{cd}/server"
  puts "Server finished"
end

sleep 2

 exec "#{cd}/seeder"

`firefox http://localhost/omega-test`

sleep 2

Process.kill 9, server_pid
